In [1]:
import numpy as np

In [2]:
np.array([1,2,3,45,5])

array([ 1,  2,  3, 45,  5])

In [4]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# 等差数组
np.arange(1,9,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8])

In [21]:
# 等距数组
np.linspace(1,9,4)
np.linspace(91,10,20)

array([91.        , 86.73684211, 82.47368421, 78.21052632, 73.94736842,
       69.68421053, 65.42105263, 61.15789474, 56.89473684, 52.63157895,
       48.36842105, 44.10526316, 39.84210526, 35.57894737, 31.31578947,
       27.05263158, 22.78947368, 18.52631579, 14.26315789, 10.        ])

In [8]:
# 二维
np.array([[1,2],[3,4],[3,3]])

array([[1, 2],
       [3, 4],
       [3, 3]])

In [15]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# 矩阵点乘
a = np.array([[1,2],[3,4]])
b = np.array([[4,52],[66,2]])
np.dot(a,b)

array([[136,  56],
       [276, 164]])

In [17]:
# 零数组
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])