In [1]:
import numpy as np

In [3]:
a = np.array(["a","b","c","sdf"])

In [4]:
a

array(['a', 'b', 'c', 'sdf'], dtype='<U3')

In [5]:
# np缺失值
np.array(["a","b","c","sdf",np.nan])

array(['a', 'b', 'c', 'sdf', 'nan'], dtype='<U3')

In [6]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
# 等差数列
np.arange(1,9,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [9]:
# 等距数列  第三个参数为元素个数
np.linspace(1,9,10)
np.linspace(1,9,3)

array([1., 5., 9.])

In [10]:
# 二维数组
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
A = np.arange(9).reshape((3,3))

In [12]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.arange(16).reshape((2,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
# 数组中的所有元素都+1
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
A+A

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [16]:
# 对应元素相乘
A*A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [18]:
print(A)
# 矩阵乘法 a矩阵的行 = b矩阵的列
# np.dot(a,b) != np.dot(b,a)
np.dot(A,A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [19]:
# 数组的维度
A.shape

(3, 3)

In [20]:
# 空数组，每个元素都非常的小
np.empty([3,4])

array([[1.11285510e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.11825337e+169, 4.32380601e-037,
        4.69762864e-033],
       [2.23078197e+160, 6.39711143e+170, 7.87102608e-071,
        4.31949579e-061]])

In [21]:
# 零数组
np.zeros([1,2])

array([[0., 0.]])

In [22]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
import pandas as pd

In [28]:
# 有两种数据类型
# 序列 Series
pd.Series()

Series([], dtype: float64)

In [31]:
X = [223,4,23,52]
pd.Series(X)

0    223
1      4
2     23
3     52
dtype: int64

In [32]:
writer = ["haimingwei","laoshe","wangxiaobo"]
age = [65,66,34]

In [33]:
s1 = pd.Series(writer)
s2 = pd.Series(age)

In [34]:
s1,s2

(0    haimingwei
 1        laoshe
 2    wangxiaobo
 dtype: object,
 0    65
 1    66
 2    34
 dtype: int64)

In [38]:
# 序列合并
# axis = 0 按行合并
pd.concat([s1,s2],axis=0)

0    haimingwei
1        laoshe
2    wangxiaobo
0            65
1            66
2            34
dtype: object

In [39]:
# axis = 1 按列合并
pd.concat([s1,s2],axis=1)

0   1
0  haimingwei  65
1      laoshe  66
2  wangxiaobo  34

In [43]:
s1[1:]

1        laoshe
2    wangxiaobo
dtype: object

In [44]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [45]:
pd.DataFrame(s1)

0
0  haimingwei
1      laoshe
2  wangxiaobo

In [53]:
pd.DataFrame(s1,columns=["X"],index=range(1,4))

X
1      laoshe
2  wangxiaobo
3         NaN

In [54]:
pd.DataFrame(s1,s2,columns=["X","Y"],index=range(1,4))

TypeError: __init__() got multiple values for argument 'index'

In [62]:
# 以字典的形式传入,直接传入index会使数据变为NaN

df = pd.DataFrame({"s1":s1.values,"s2":s2.values},index=[1,2,3])

In [66]:
# 给DataFrame新增一列直接用名字即可
df['s3'] = df['s2']*2

In [67]:
df

s1  s2   s3
1  haimingwei  65  130
2      laoshe  66  132
3  wangxiaobo  34   68

In [68]:
# 删除数据框
del df["s3"]

In [69]:
df

s1  s2
1  haimingwei  65
2      laoshe  66
3  wangxiaobo  34

In [75]:
# 读取excel文件
pd.read_csv("DaPy_data.csv")

房屋信息   房屋价格   房屋位置         房屋单价
0             骏景花园  | 3室2厅 | 105平米 | 南 北 | 简装 | 有电梯  490.0     棠下  单价46667元/平米
1            华景新城怡华台  | 3室2厅 | 91平米 | 西南 | 精装 | 有电梯  480.0   华景新城  单价52748元/平米
2             芳草园  | 3室2厅 | 117.05平米 | 北 | 简装 | 有电梯  850.0    天河北  单价72619元/平米
3        保利百合花园二期  | 2室1厅 | 72.27平米 | 西南 | 精装 | 有电梯  315.0    江燕路  单价43587元/平米
4           汇侨新城东区  | 2室1厅 | 75.5平米 | 东北 | 简装 | 无电梯  186.0     新市  单价24636元/平米
...                                             ...    ...    ...          ...
2995       光大花园中海锦榕湾  | 3室1厅 | 102平米 | 南 | 其他 | 有电梯  730.0  工业大道北  单价71569元/平米
2996              东浚荔景苑  | 3室1厅 | 95.97平米 | 东北 | 简装  415.0    中山八  单价43243元/平米
2997  广州雅居乐花园剑桥郡  | 3室2厅 | 128.63平米 | 东南 | 其他 | 有电梯  560.0     华南  单价43536元/平米
2998           泓景花园  | 3室2厅 | 110平米 | 东北 | 其他 | 有电梯  650.0     赤岗  单价59091元/平米
2999        下塘西路  | 3室2厅 | 121.02平米 | 西北 | 其他 | 无电梯  480.0     麓景  单价39663元/平米

[3000 rows x 4 columns]

In [72]:
# 读粘贴板数据
df2 = pd.read_clipboard()

In [73]:
df2

房屋信息   房屋价格   房屋位置         房屋单价
0             骏景花园  | 3室2厅 | 105平米 | 南 北 | 简装 | 有电梯  490.0     棠下  单价46667元/平米
1            华景新城怡华台  | 3室2厅 | 91平米 | 西南 | 精装 | 有电梯  480.0   华景新城  单价52748元/平米
2             芳草园  | 3室2厅 | 117.05平米 | 北 | 简装 | 有电梯  850.0    天河北  单价72619元/平米
3        保利百合花园二期  | 2室1厅 | 72.27平米 | 西南 | 精装 | 有电梯  315.0    江燕路  单价43587元/平米
4           汇侨新城东区  | 2室1厅 | 75.5平米 | 东北 | 简装 | 无电梯  186.0     新市  单价24636元/平米
...                                             ...    ...    ...          ...
2995       光大花园中海锦榕湾  | 3室1厅 | 102平米 | 南 | 其他 | 有电梯  730.0  工业大道北  单价71569元/平米
2996              东浚荔景苑  | 3室1厅 | 95.97平米 | 东北 | 简装  415.0    中山八  单价43243元/平米
2997  广州雅居乐花园剑桥郡  | 3室2厅 | 128.63平米 | 东南 | 其他 | 有电梯  560.0     华南  单价43536元/平米
2998           泓景花园  | 3室2厅 | 110平米 | 东北 | 其他 | 有电梯  650.0     赤岗  单价59091元/平米
2999        下塘西路  | 3室2厅 | 121.02平米 | 西北 | 其他 | 无电梯  480.0     麓景  单价39663元/平米

[3000 rows x 4 columns]

In [2]:
import pandas as pd

In [11]:
pd.read_excel("DaPy_data.xlsx")

XLRDError: Excel xlsx file; not supported

In [10]:
pip install xlrd

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\g2018\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.


In [9]:
!pip install --upgrade pip --user

In [12]:
print( "hello" +"world")

helloworld


In [13]:
from math import sqrt

In [14]:
print(sqrt(3)*sqrt(3)==3)

False


In [15]:
"Happy New Year"[3:8]

'py Ne'

In [16]:
type(1+2L*3.14)

SyntaxError: invalid syntax (<ipython-input-16-6bee0a5eade3>, line 1)

In [18]:
import math

In [19]:
math.log(1000)

6.907755278982137

In [22]:
k = 1000
count=0
while k>1:
    count+=1
    print(k)
    k=k/2
print(count)

1000
500.0
250.0
125.0
62.5
31.25
15.625
7.8125
3.90625
1.953125
10


In [26]:
for i in (123,2):
    print(i)

123
2


In [29]:
def func(s,i,j):
    if i<j:
        func(s,i+1,j-1)
        s[i],s[j]=s[j],s[i]

def main():
    a = [10,6,23,-90,0,3]
    func(a,0,len(a)-1)
    for i in range(6):
        print(a[i])
        print("\n")

main()

3


0


-90


23


6


10




In [31]:
i = 1
while i<10:
    if i>4:
        break
    else:
        print(i)
        i+=1

1
2
3
4


In [35]:
def foo(s):
    if s=="":
        return s
    else:
        return foo(s[1:])+s[0]
print(foo("Happy New Year"))

raeY weN yppaH


In [36]:
1/4+2.75

3.0